apiVersion : apps/v1
kind: Deployment
metadata:
  name: reqres_delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reqres_delivery
  template:
    metadata:
      labels:
        app: reqres_delivery
    spec:
      containers:
        - name: reqres_delivery
          image: admin10acr.azurecr.io/reqres_delivery
          ports:
            - containerPort: 8080
