apiVersion : apps/v1
kind: Deployment
metadata:
  name: reqres-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reqres-delivery
  template:
    metadata:
      labels:
        app: reqres-delivery
    spec:
      containers:
        - name: reqres-delivery
          image: admin10acr.azurecr.io/reqres_delivery
          ports:
            - containerPort: 8080
